### ISSUE TITLE
Change shebang to allow non-system Perl interpreters?

### ISSUE THREAD

**Issue by ljliman** [verisign/yazvs#2]
This is just a small feature request. Would you please consider changing the shebang line of the main program (and others, if there are any) from

`#!/usr/bin/perl`

to 

`#!/usr/bin/env perl`

That makes the script execute the perl interpreter that comes first in your path, which may be a "$better" one than the one installed in your system binaries. One typical platform from "where you want this" is on macOS, where the system Perl is 8 versions behind ...

Of course there are reasons to keep it as it is, and YMMV on this, which I respect.

Cheers
  /Liman

**Comment by wessels** [comment]
Done with 6f661d08ad0225c04211bb70e40a349cc8ced957.
